### ISSUE TITLE
Use for Koi Pond and integration in Homeassistant

### ISSUE THREAD

**Issue by DirkTas67** [hydromisc/hydromisc#2]
Hello,

I'm very interested in this project to manage my koi pond, however I would like it to integrate in Homeassistant.
I suspect every function runs on the esp32 and the 'rest'of the components are there to let input and output function correctly, just correct me if i'm wrong.

I ordered the pcb and the parts and i have most of the thing allready here except for a few parts I still have to receive from digikey.

I don't know if you know the esphome project at https://esphome.io/, with this you can probably do most of the things you allready did in your code, but esphome devices can simply be added in homeassistant.

The great advantage of ESPHome is that the device can run independatly.

Maybe you can look into it?

Regards,
Dirk

**Comment by hydromisc** [comment]
Cool, and let us know how the build goes. I don't keep an aquarium or pond, but the basic requirements (measure EC, pH, temperature, etc., dose chemicals, control pumps) seem very similar.

I'm aware of the ESPHome project, though not deeply familiar. I believe that out of the box, it could interface to some parts of the I/O that I'm using (e.g., the pH sensor, which to the ESP32 is just an analog voltage input, or the AM230x temperature and humidity sensors), but not others (e.g., the EC sensors, which require multiple measurements properly sequenced in time, or, significantly, all the pump/solenoid outputs since they're through a shift register functioning as a GPIO expander).

So I believe some additions to the ESPHome firmware would be required to properly support this board. I have no time for that work myself, but I believe it could be quite valuable if anyone wanted to take that on (or otherwise integrate with home automation software), definitely the preferred programming approach for a lot of people.
